def clean_text(text):
    cleaned_text = text.lower()
    cleaned_text = cleaned_text.replace(" ", "")
    cleaned_text = cleaned_text.replace('á', 'a')
    cleaned_text = cleaned_text.replace('é', 'e')
    cleaned_text = cleaned_text.replace('í', 'i')
    cleaned_text = cleaned_text.replace('ó', 'o')
    cleaned_text = cleaned_text.replace('ú', 'u')
    cleaned_text = cleaned_text.replace("'", "")
    cleaned_text = cleaned_text.replace(".", "")
    cleaned_text = cleaned_text.replace(",", "")
    cleaned_text = cleaned_text.replace(";", "")
    cleaned_text = cleaned_text.replace(":", "")
    cleaned_text = cleaned_text.replace("!", "")
    cleaned_text = cleaned_text.replace("?", "")
    cleaned_text = cleaned_text.replace("¿", "")
    cleaned_text = cleaned_text.replace("¡", "")
    cleaned_text = cleaned_text.replace("(", "")
    cleaned_text = cleaned_text.replace(")", "")
    cleaned_text = cleaned_text.replace("[", "")
    cleaned_text = cleaned_text.replace("]", "")
    cleaned_text = cleaned_text.replace("{", "")
    cleaned_text = cleaned_text.replace("}", "")
    cleaned_text = cleaned_text.replace("\\", "")
    cleaned_text = cleaned_text.replace("/", "")
    cleaned_text = cleaned_text.replace("*", "")
    cleaned_text = cleaned_text.replace("^", "")
    cleaned_text = cleaned_text.replace("+", "")
    cleaned_text = cleaned_text.replace("-", "")
    cleaned_text = cleaned_text.replace("_", "")
    cleaned_text = cleaned_text.replace("=", "")
    cleaned_text = cleaned_text.replace("|", "")
    cleaned_text = cleaned_text.replace(":", "")
    cleaned_text = cleaned_text.replace(";", "")
    cleaned_text = cleaned_text.replace("'", "")
    cleaned_text = cleaned_text.replace('\n', "")
    return cleaned_text
